import { type SVGAttributes } from 'react';

export type IconProps = SVGAttributes<SVGElement>;

export { AppleIcon } from './icons/AppleIcon';
export { ArrowLeftIcon } from './icons/ArrowLeftIcon';
export { LogoIcon } from './icons/LogoIcon';
export { ArrowRightIcon } from './icons/ArrowRightIcon';
export { ArrowUpRightIcon } from './icons/ArrowUpRightIcon';
export { MenuTriggerIcon } from './icons/MenuTrigger';
export { EyeCloseIcon } from './icons/EyeCloseIcon';
export { EyeOpenIcon } from './icons/EyeOpenIcon';
export { HomeIcon } from './icons/HomeIcon';
export { UserArrowLeftIcon } from './icons/UserArrowLeftIcon';
export { UserSecurityIcon } from './icons/UserSecurityIcon';
export { MoonIcon } from './icons/MoonIcon';
export { SunIcon } from './icons/SunIcon';
export { XIcon } from './icons/XIcon';
export { GitHubBrandIcon } from './icons/GitHubBrandIcon';
export { GitHubIcon } from './icons/GitHubIcon';
export { GoogleBrandIcon } from './icons/GoogleBrandIcon';
export { CalendarIcon } from './icons/CalendarIcon';
export { CursorClickIcon } from './icons/CursorClickIcon';
export { PencilSwooshIcon } from './icons/PencilSwooshIcon';
export { SubscriberIcon } from './icons/SubscriberIcon';
export { TiltedSendIcon } from './icons/TiltedSendIcon';
export { UTurnLeftIcon } from './icons/UTurnLeftIcon';
export { TagIcon } from './icons/TagIcon';
export { EmptyIcon } from './icons/EmptyIcon';
export { MailIcon } from './icons/MailIcon';
export { PannelLeftIcon } from './icons/PannelLeftIcon';
export { RSSIcon } from './icons/RSSIcon';
export { DashboardIcon } from './icons/DashboardIcon';
export { NotebookIcon } from './icons/NotebookIcon';
export { MailboxIcon } from './icons/MailboxIcon';
export { UsersIcon } from './icons/UsersIcon';
export { SettingIcon } from './icons/SettingIcon';
export { SearchIcon } from './icons/SearchIcon';
export { LightningIcon } from './icons/LightningIcon';
